const Icons = {
  Add: "fa-solid fa-plus",
  Attachment: "fa-solid fa-paperclip",
  Edit: "fa-solid fa-pen",
  Delete: "fa-regular fa-trash-can",
  Copy: "fa-solid fa-clone",
  Details: "fa-solid fa-list",
  Refresh: "fa-solid fa-rotate-right",
  EditContext: "fa-solid fa-pen",
  DeleteContext: "fa-regular fa-trash-can",
  DetailsContext: "fa-solid fa-list",
  ExcelExport: "fa-solid fa-file-excel",
  Email: "fa-regular fa-envelope",
  Calendar: "fa-regular fa-calendar-days",
  Clear: "fa-solid fa-filter-circle-xmark",
  Template: "fa-regular fa-file-code",
  Import: "fa-solid fa-file-import",
  Export: "fa-solid fa-file-export",
  Download: "fa-solid fa-download",
  Upload: "fa-solid fa-upload",
  Comments: "fa-regular fa-comments",
  Send: "fa-regular fa-paper-plane",
  Print: "fa-solid fa-print",
  Accept: "fa-solid fa-check",
  Reject: "fa-solid fa-xmark",
  Schedule: "fa-regular fa-calendar-days",
  FieldReport: "fa-regular fa-map",
  ShiftReport: "fa-regular fa-comments",
  Important: "fa-solid fa-circle-exclamation",
  CreateNdtRequest: "fa-solid fa-flask",
  Spin: "fa-solid fa-spinner fa-spin",
};

export default Icons;
